---

- name: Install Apache.
  package:
    name:
      - apache2
      - php
      - php-mysql
- name: Make my directory tree readable
  file:
    path: /var/www/html/
    mode: u=rwX,g=rX,o=rX
    recurse: yes
    owner: www-data
    group: www-data
- name: Make sure Apache is started now and at boot.
  service: name=apache2 state=started enabled=yes
- name: Ansible delete file example
  file:
    path: /var/www/html/index.html
    state: absent